export const FEED_PAGE_DEFAULT_LIMIT = 10;
export const FEED_PAGE_MAX_LIMIT = 20;
export const POST_PAGE_REVALIDATE_SECONDS = 300;
export const BLOG_SHELL_CACHE_TAG = 'blog-shell';
export const BLOG_SHELL_REVALIDATE_SECONDS = 300;

export const SEARCH_DROPDOWN_MIN_QUERY = 2;
export const SEARCH_DROPDOWN_DEBOUNCE_MS = 250;
export const SEARCH_DROPDOWN_MAX_QUERY_LENGTH = 64;
export const SEARCH_DROPDOWN_LIMIT = 8;

export const ZIP_UPLOAD_MAX_SIZE_BYTES = 10 * 1024 * 1024;

export const LOGIN_RATE_LIMIT_MAX_ATTEMPTS = 5;
export const LOGIN_RATE_LIMIT_WINDOW_MS = 60 * 1000;
export const LOGIN_RATE_LIMIT_CLEANUP_INTERVAL = 100;
export const LOGIN_RATE_LIMIT_MAX_KEYS = 5000;
